import assert from 'node:assert/strict';
import test from 'node:test';
import { executeChatGPTWebModel } from '../server/chatgptWebBrain.js';
import { executeModelToolLoop } from '../server/modelToolLoop.js';
import { createRun, transitionRun } from '../server/runEngine.js';
import { TOOL_CALL_END, TOOL_CALL_START } from '../server/chatgptWebProtocol.js';

const toolBlock = (calls) => `${TOOL_CALL_START}\n${JSON.stringify({ calls })}\n${TOOL_CALL_END}`;
function fixture(request = 'Show my tasks') { const state = { chatgptWeb: { enabled: true, sessionUrl: null, turns: 0 }, tasks: [], memories: [], workflows: [], approvals: [], runs: [], activity: [], runtime: {}, modelRouting: {} }; const run = createRun({ type: 'chat', request, plan: { goal: request, intent: 'tool', steps: [] } }); transitionRun(run, 'running'); state.runs.push(run); return { state, run, route: { primaryModel: 'chatgpt-web' } }; }
function transport(replies) { return { sent: [], options: [], resets: 0, async send(prompt, options) { this.sent.push(prompt); this.options.push(options); const text = replies.shift(); if (text instanceof Error) throw text; return { text, sessionUrl: 'https://chatgpt.com/c/test' }; }, async reset() { this.resets += 1; } }; }
const schemas = [{ type: 'function', function: { name: 'tasks__list', description: 'List tasks', parameters: { type: 'object', properties: {} } } }];

test('web brain answers without a tool and persists only session metadata', async () => { const f = fixture('Hello'); const mock = transport(['Hello.']); const result = await executeChatGPTWebModel({ request: 'Hello', state: f.state, continuationState: { runId: f.run.id }, tools: schemas, transport: mock }); assert.equal(result.reply, 'Hello.'); assert.equal(f.state.chatgptWeb.sessionUrl, 'https://chatgpt.com/c/test'); assert.equal(result.provider, 'chatgpt-web'); });
test('web brain performs one canonical tool through the existing model loop', async () => { const f = fixture(); const mock = transport([toolBlock([{ id: 'list', name: 'tasks__list', arguments: {} }]), 'You have no tasks.']); const executeModel = (options) => executeChatGPTWebModel({ ...options, transport: mock }); const result = await executeModelToolLoop({ ...f, request: f.run.request, executeModel }); assert.equal(result.status, 'completed'); assert.equal(result.toolResults[0].toolName, 'tasks.list'); assert.equal(result.toolResults[0].verified, true); assert.match(mock.sent[1], /JARVIS_TOOL_RESULTS/); });
test('web brain supports sequential tool reasoning without a second executor', async () => { const f = fixture(); const mock = transport([toolBlock([{ id: 'a', name: 'tasks__list', arguments: {} }]), toolBlock([{ id: 'b', name: 'tasks__list', arguments: {} }]), 'Checked twice.']); const executeModel = (options) => executeChatGPTWebModel({ ...options, transport: mock }); const result = await executeModelToolLoop({ ...f, request: f.run.request, executeModel }); assert.equal(result.toolResults.length, 2); assert.equal(result.reply, 'Checked twice.'); });
test('browser errors remain structured and do not crash the assistant process', async () => { const f = fixture(); const failure = Object.assign(new Error('login required'), { code: 'CHATGPT_LOGIN_REQUIRED' }); const mock = transport([failure]); await assert.rejects(() => executeChatGPTWebModel({ request: 'Hello', state: f.state, continuationState: { runId: f.run.id }, tools: schemas, transport: mock }), (error) => error.code === 'CHATGPT_LOGIN_REQUIRED'); assert.equal(f.state.chatgptWeb.lastError.code, 'CHATGPT_LOGIN_REQUIRED'); });
test('repeated identical calls stop at a bounded duplicate-call guard', async () => { const f = fixture(); const same = toolBlock([{ id: 'repeat', name: 'tasks__list', arguments: {} }]); const mock = transport([same, same, same]); const executeModel = (options) => executeChatGPTWebModel({ ...options, transport: mock }); await assert.rejects(() => executeModelToolLoop({ ...f, request: f.run.request, maxRounds: 4, executeModel }), (error) => error.code === 'TOOL_LOOP_LIMIT'); });
test('configured conversation replaces a stale persisted URL after restart', async () => { const f = fixture('Continue'); f.state.chatgptWeb.sessionUrl = 'https://chatgpt.com/c/persisted'; f.state.chatgptWeb.bootstrapped = true; const mock = transport(['Continued.']); await executeChatGPTWebModel({ request: 'Continue', state: f.state, continuationState: { runId: f.run.id }, tools: schemas, transport: mock }); assert.match(mock.options[0].sessionUrl, /\/c\/6aa171a5-72fc-83e8-ac5f-1a3b70424a6a$/); assert.doesNotMatch(mock.sent[0], /You are the reasoning engine/); });
test('session threshold rotates and reboots compact context', async () => { const prior = process.env.JARVIS_CHATGPT_MAX_SESSION_TURNS; process.env.JARVIS_CHATGPT_MAX_SESSION_TURNS = '4'; const f = fixture('Continue'); f.state.chatgptWeb.turns = 4; f.state.chatgptWeb.bootstrapped = true; const mock = transport(['Fresh.']); try { await executeChatGPTWebModel({ request: 'Continue', state: f.state, continuationState: { runId: f.run.id }, tools: schemas, transport: mock }); assert.equal(mock.resets, 1); assert.match(mock.sent[0], /You are the reasoning engine/); } finally { if (prior === undefined) delete process.env.JARVIS_CHATGPT_MAX_SESSION_TURNS; else process.env.JARVIS_CHATGPT_MAX_SESSION_TURNS = prior; } });
test('approval-requiring web call pauses in the canonical executor', async () => { const f = fixture('Run node version'); const mock = transport([toolBlock([{ id: 'cmd', name: 'command__execute', arguments: { command: 'node --version' } }])]); const executeModel = (options) => executeChatGPTWebModel({ ...options, transport: mock }); const result = await executeModelToolLoop({ ...f, request: f.run.request, executeModel }); assert.equal(result.status, 'waiting_for_approval'); assert.equal(result.toolResults[0].error.code, 'APPROVAL_REQUIRED'); });
test('per-response call limit rejects tool floods before execution', async () => { const prior = process.env.JARVIS_CHATGPT_MAX_CALLS_PER_STEP; process.env.JARVIS_CHATGPT_MAX_CALLS_PER_STEP = '1'; const f = fixture(); const mock = transport([toolBlock([{ name: 'tasks__list', arguments: {} }, { name: 'tasks__list', arguments: {} }])]); try { await assert.rejects(() => executeChatGPTWebModel({ request: f.run.request, state: f.state, continuationState: { runId: f.run.id }, tools: schemas, transport: mock }), (error) => error.code === 'TOOL_LOOP_LIMIT'); } finally { if (prior === undefined) delete process.env.JARVIS_CHATGPT_MAX_CALLS_PER_STEP; else process.env.JARVIS_CHATGPT_MAX_CALLS_PER_STEP = prior; } });
test('every JARVIS session uses the configured persistent ChatGPT conversation instead of the project home', async () => { const f = fixture('First'); f.state.chatSessions = [{ id: 'one', chatgptConversationUrl: null, chatgptBootstrapped: false, chatgptTurns: 0 }, { id: 'two', chatgptConversationUrl: null, chatgptBootstrapped: false, chatgptTurns: 0 }]; const mock = transport(['One answer', 'Two answer']); mock.send = async function(prompt, options) { this.sent.push(prompt); this.options.push(options); return { text: this.sent.length === 1 ? 'One answer' : 'Two answer', sessionUrl: options.sessionUrl, projectUrl: 'https://chatgpt.com/g/g-p-jarvis/project' }; }; await executeChatGPTWebModel({ request: 'First', state: f.state, continuationState: { runId: f.run.id, conversationId: 'one' }, tools: schemas, transport: mock }); await executeChatGPTWebModel({ request: 'Second', state: f.state, continuationState: { runId: f.run.id, conversationId: 'two' }, tools: schemas, transport: mock }); for (const options of mock.options) { assert.equal(options.newSession, false); assert.match(options.sessionUrl, /\/c\/6aa171a5-72fc-83e8-ac5f-1a3b70424a6a$/); assert.equal(options.projectName, 'jarvis-chat'); } assert.equal(f.state.chatSessions[0].chatgptConversationUrl, f.state.chatSessions[1].chatgptConversationUrl); });
