import assert from 'node:assert/strict';
import test from 'node:test';
import { defaultPools, executeModelPool, failureClass, normalizeModality } from '../server/modelPool.js';
import { selectLogicalModel } from '../server/modelRouting.js';
import { routeRequest } from '../server/router.js';

const originalPools = process.env.MODEL_PROVIDER_POOLS;
const providers = (model, count, prefix = model) => Array.from({ length: count }, (_, index) => ({ id: `${prefix}-${index + 1}`, provider: 'test', baseUrl: `https://${prefix}-${index + 1}.test/v1`, modelId: model, credentialRef: `TEST_KEY_${index + 1}` }));
function setup(deepseek = 3, glm = 2, extra = {}) { process.env.TEST_KEY_1 = 'a'; process.env.TEST_KEY_2 = 'b'; process.env.TEST_KEY_3 = 'c'; process.env.MODEL_PROVIDER_POOLS = JSON.stringify({ 'deepseek-v4-flash': providers('deepseek-v4-flash', deepseek, 'deepseek'), 'glm-5.2': providers('glm-5.2', glm, 'glm'), ...extra }); return { modelRouting: { providerHealth: {} } }; }
function response(status, body = {}, headers = {}) { return { ok: status >= 200 && status < 300, status, headers: new Headers(headers), json: async () => body }; }
const success = (text = 'ok') => response(200, { choices: [{ message: { content: text } }], usage: { total_tokens: 3 } });

test('default OpenRouter model IDs match the live provider catalog', () => {
  const pools = defaultPools();
  assert.equal(pools['muse-spark-1.2'][0].modelId, 'meta/muse-spark-1.2');
  assert.equal(pools['nemotron-3-nano-omni'][0].modelId, 'nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free');
});

test.after(() => { if (originalPools === undefined) delete process.env.MODEL_PROVIDER_POOLS; else process.env.MODEL_PROVIDER_POOLS = originalPools; delete process.env.TEST_KEY_1; delete process.env.TEST_KEY_2; delete process.env.TEST_KEY_3; });

test('DeepSeek API1 succeeds without rotation', async () => { const state = setup(); let calls = 0; const result = await executeModelPool({ logicalModel: 'deepseek-v4-flash', request: 'hello', state, fetchImpl: async () => { calls += 1; return success(); } }); assert.equal(calls, 1); assert.equal(result.routingTelemetry.apiRotationCount, 0); assert.equal(result.logicalModel, 'deepseek-v4-flash'); });
test('model requests use a bounded output-token budget', async () => { const state = setup(); let sent; await executeModelPool({ logicalModel: 'deepseek-v4-flash', request: 'hello', state, fetchImpl: async (_url, init) => { sent = JSON.parse(init.body); return success(); } }); assert.equal(sent.max_tokens, 2048); });
test('DeepSeek rotates from exhausted API1 to API2', async () => { const state = setup(); let calls = 0; const result = await executeModelPool({ logicalModel: 'deepseek-v4-flash', request: 'hello', state, fetchImpl: async () => ++calls === 1 ? response(429, { error: { message: 'quota exhausted' } }) : success() }); assert.equal(result.provider, 'deepseek-2'); assert.equal(state.modelRouting.providerHealth['deepseek-1'].status, 'QUOTA_EXHAUSTED'); });
test('DeepSeek API3 succeeds after first two are exhausted', async () => { const state = setup(); let calls = 0; const result = await executeModelPool({ logicalModel: 'deepseek-v4-flash', request: 'hello', state, fetchImpl: async () => ++calls < 3 ? response(429, { error: { message: 'quota exhausted' } }) : success() }); assert.equal(result.provider, 'deepseek-3'); });
test('all DeepSeek providers exhausted falls back to GLM', async () => { const state = setup(2, 1); const result = await executeModelPool({ logicalModel: 'deepseek-v4-flash', request: 'hello', state, fetchImpl: async (url) => url.includes('deepseek') ? response(429, { error: { message: 'quota exhausted' } }) : success('glm') }); assert.equal(result.logicalModel, 'glm-5.2'); assert.equal(result.routingTelemetry.modelFallbackUsed, true); });
test('GLM fallback provider succeeds', async () => { const state = setup(1, 2); const result = await executeModelPool({ logicalModel: 'deepseek-v4-flash', request: 'hello', state, fetchImpl: async (url) => url.includes('glm-2') ? success() : response(429, { error: { message: 'quota exhausted' } }) }); assert.equal(result.provider, 'glm-2'); });
test('all DeepSeek and GLM providers exhausted returns clean capacity failure with telemetry', async () => { const state = setup(1, 1); await assert.rejects(() => executeModelPool({ logicalModel: 'deepseek-v4-flash', request: 'hello', state, fetchImpl: async () => response(429, { error: { message: 'quota exhausted' } }) }), (error) => error.code === 'MODEL_CAPACITY_EXHAUSTED' && error.routingTelemetry.fallbackTo === 'glm-5.2'); });
test('malformed 400 does not rotate', async () => { const state = setup(); let calls = 0; await assert.rejects(() => executeModelPool({ logicalModel: 'deepseek-v4-flash', request: 'hello', state, fetchImpl: async () => { calls += 1; return response(400, { error: { message: 'invalid schema' } }); } }), (error) => error.code === 'REQUEST_ERROR'); assert.equal(calls, 1); });
test('429 creates cooldown and rotates', async () => { const state = setup(); let calls = 0; await executeModelPool({ logicalModel: 'deepseek-v4-flash', request: 'hello', state, fetchImpl: async () => ++calls === 1 ? response(429, { error: { message: 'rate limited' } }, { 'retry-after': '2' }) : success(), now: () => 1_000 }); assert.equal(state.modelRouting.providerHealth['deepseek-1'].status, 'RATE_LIMITED'); assert.equal(state.modelRouting.providerHealth['deepseek-1'].retryAfter, new Date(3_000).toISOString()); });
test('temporary 5xx retries once then rotates', async () => { const state = setup(2, 1); let calls = 0; const result = await executeModelPool({ logicalModel: 'deepseek-v4-flash', request: 'hello', state, fetchImpl: async (url) => { calls += 1; return url.includes('deepseek-1') ? response(503, { error: { message: 'capacity' } }) : success(); } }); assert.equal(calls, 3); assert.equal(result.provider, 'deepseek-2'); });
test('manual DeepSeek selection overrides automatic coding route', () => { const route = selectLogicalModel('implement a distributed repository architecture', { modelMode: 'manual', manualModel: 'deepseek-v4-flash' }); assert.equal(route.primaryModel, 'deepseek-v4-flash'); assert.equal(route.routingMode, 'manual'); assert.deepEqual(route.supportModels, []); });
test('manual Laguna exhausts its pool then falls back to GLM', async () => { const state = setup(0, 1, { 'laguna-s-2.1': providers('laguna-s-2.1', 1, 'laguna') }); const result = await executeModelPool({ logicalModel: 'laguna-s-2.1', request: 'code', state, fetchImpl: async (url) => url.includes('laguna') ? response(429, { error: { message: 'quota exhausted' } }) : success() }); assert.equal(result.logicalModel, 'glm-5.2'); });
test('unsupported GLM modality returns capability unavailable after Nano pool exhaustion', async () => { const state = setup(0, 1, { 'nemotron-3-nano-omni': providers('nano', 1, 'nano') }); await assert.rejects(() => executeModelPool({ logicalModel: 'nemotron-3-nano-omni', request: 'see image', requiredModality: 'image', state, fetchImpl: async () => response(429, { error: { message: 'quota exhausted' } }) }), (error) => error.code === 'CAPABILITY_UNAVAILABLE'); });
test('Lightning outage does not block deterministic or Normal-mode routing', () => { assert.equal(routeRequest('show my tasks').route, 'TOOL_CALL'); assert.equal(selectLogicalModel('hello', { modelMode: 'auto', jarvisMode: 'normal' }).primaryModel, 'muse-spark-1.2'); });
test('three JARVIS modes select their requested default model', () => { assert.equal(selectLogicalModel('hello', { jarvisMode: 'normal' }).primaryModel, 'muse-spark-1.2'); assert.equal(selectLogicalModel('hello', { jarvisMode: 'coding' }).primaryModel, 'laguna-s-2.1'); assert.equal(selectLogicalModel('hello', { jarvisMode: 'deepthinking' }).primaryModel, 'glm-5.2'); });
test('enabled ChatGPT Web can become the general brain without replacing specialist routes', () => { const settings = { jarvisMode: 'normal', chatgptWeb: { enabled: true, useAsDefault: true } }; assert.equal(selectLogicalModel('hello', settings).primaryModel, 'chatgpt-web'); assert.equal(selectLogicalModel('implement this repository feature', settings).primaryModel, 'laguna-s-2.1'); });
test('manual ChatGPT Web override takes priority', () => assert.equal(selectLogicalModel('hello', { modelMode: 'manual', manualModel: 'chatgpt-web' }).primaryModel, 'chatgpt-web'));
test('manual ChatGPT Web preserves tool intent for arbitrary app and RAM requests', () => {
  const route = selectLogicalModel('Open Notepad and inspect the running processes by RAM usage', { modelMode: 'manual', manualModel: 'chatgpt-web' });
  assert.equal(route.primaryModel, 'chatgpt-web');
  assert.equal(route.requiresTools, true);
  assert.equal(route.taskType, 'computer_use');
});
test('image and video creation route directly to Gemini media generation', () => { assert.deepEqual(routeRequest('create an image of a gold neural brain').args.kind, 'image'); assert.deepEqual(routeRequest('make a video of a flying robot').args.kind, 'video'); });
test('concurrent requests distribute across equally healthy providers', async () => { const state = setup(2, 1); let release; const gate = new Promise((resolve) => { release = resolve; }); const seen = []; const fetchImpl = async (url) => { seen.push(url); if (url.includes('deepseek-1')) await gate; return success(); }; const first = executeModelPool({ logicalModel: 'deepseek-v4-flash', request: 'one', state, fetchImpl }); await new Promise((resolve) => setTimeout(resolve, 0)); const second = executeModelPool({ logicalModel: 'deepseek-v4-flash', request: 'two', state, fetchImpl }); release(); await Promise.all([first, second]); assert.ok(seen.some((url) => url.includes('deepseek-1'))); assert.ok(seen.some((url) => url.includes('deepseek-2'))); });
test('provider becomes eligible after cooldown expires', async () => { const state = setup(2, 1); state.modelRouting.providerHealth['deepseek-1'] = { status: 'RATE_LIMITED', retryAfter: new Date(2_000).toISOString() }; const result = await executeModelPool({ logicalModel: 'deepseek-v4-flash', request: 'hello', state, now: () => 3_000, fetchImpl: async () => success() }); assert.equal(result.provider, 'deepseek-1'); });
test('failure classification separates request bugs from provider failures', () => { assert.equal(failureClass(400, 'bad schema'), 'REQUEST_ERROR'); assert.equal(failureClass(429, 'quota exhausted'), 'QUOTA_EXHAUSTED'); assert.equal(failureClass(503, 'down'), 'TEMPORARILY_UNAVAILABLE'); });
test('MIME attachment types normalize to model capability names', () => { assert.equal(normalizeModality('image/png'), 'image'); assert.equal(normalizeModality('audio/webm'), 'audio'); assert.equal(normalizeModality('application/pdf'), 'text'); });
test('valid image input is passed to the perception provider', async () => { const state = setup(0, 1, { 'nemotron-3-nano-omni': providers('nano', 1, 'nano').map((item) => ({ ...item, modalities: ['text', 'image'] })) }); let sent; await executeModelPool({ logicalModel: 'nemotron-3-nano-omni', request: 'inspect', requiredModality: 'image/png', attachments: [{ type: 'image/png', dataUrl: 'data:image/png;base64,AA==' }], state, fetchImpl: async (_url, init) => { sent = JSON.parse(init.body); return success(); } }); assert.equal(sent.messages.at(-1).content[1].type, 'image_url'); });
test('model-unavailable response rotates while an unrelated malformed 400 does not', async () => { const state = setup(); let calls = 0; const result = await executeModelPool({ logicalModel: 'deepseek-v4-flash', request: 'hello', state, fetchImpl: async () => ++calls === 1 ? response(404, { error: { message: 'model does not exist on this endpoint' } }) : success() }); assert.equal(result.provider, 'deepseek-2'); assert.equal(state.modelRouting.providerHealth['deepseek-1'].status, 'MODEL_UNAVAILABLE'); });
test('empty successful response gets one retry then rotates providers', async () => { const state = setup(2, 1); let calls = 0; const result = await executeModelPool({ logicalModel: 'deepseek-v4-flash', request: 'hello', state, fetchImpl: async (url) => { calls += 1; return url.includes('deepseek-1') ? response(200, { choices: [] }) : success(); } }); assert.equal(calls, 3); assert.equal(result.provider, 'deepseek-2'); });
test('MiniMax exhaustion does not fall back to GLM without computer-use capability', async () => { const state = setup(0, 1, { 'minimax-m3': providers('minimax-m3', 1, 'minimax') }); await assert.rejects(() => executeModelPool({ logicalModel: 'minimax-m3', request: 'click', requiredCapability: 'computer_use', state, fetchImpl: async () => response(429, { error: { message: 'quota exhausted' } }) }), (error) => error.code === 'CAPABILITY_UNAVAILABLE'); });
test('configured GLM computer-use capability permits MiniMax fallback', async () => { const state = setup(0, 0, { 'minimax-m3': providers('minimax-m3', 1, 'minimax'), 'glm-5.2': providers('glm-5.2', 1, 'glm').map((item) => ({ ...item, capabilities: ['computer_use'] })) }); const result = await executeModelPool({ logicalModel: 'minimax-m3', request: 'click', requiredCapability: 'computer_use', state, fetchImpl: async (url) => url.includes('minimax') ? response(429, { error: { message: 'quota exhausted' } }) : success() }); assert.equal(result.logicalModel, 'glm-5.2'); });
