import test from 'node:test';
import assert from 'node:assert/strict';
import { routeIncomingRequest, requestComplexity } from '../server/requestRouter.js';
import { getToolDefinition } from '../server/registry.js';

const tool = getToolDefinition('system.resources');
const needle = (result) => ({ classifyOrCall: async () => ({ latencyMs: 12, ...result }) });

test('deterministic commands remain Level 0 and do not invoke Needle', async () => { let calls = 0; const decision = await routeIncomingRequest('mute', { needle: { classifyOrCall: async () => { calls += 1; } } }); assert.equal(decision.route, 'DETERMINISTIC'); assert.equal(decision.tool, 'audio.mute'); assert.equal(calls, 0); });
test('high-confidence Needle proposal becomes one canonical validated ToolCall', async () => { const decision = await routeIncomingRequest('show current system resource usage', { deterministicRoute: { route: 'MODEL', confidence: 0.7 }, tools: [tool], needle: needle({ function_calls: [{ name: 'system__resources', arguments: {} }], confidence: 0.96 }) }); assert.equal(decision.route, 'NEEDLE'); assert.equal(decision.tool, 'system.resources'); assert.deepEqual(decision.arguments, {}); });
test('calibrated read-only threshold does not weaken the side-effect threshold', async () => { const read = await routeIncomingRequest('resource status', { deterministicRoute: { route: 'MODEL', confidence: 0.7 }, tools: [tool], needle: needle({ function_calls: [{ name: 'system__resources', arguments: {} }], confidence: 0.87 }) }); assert.equal(read.route, 'NEEDLE'); const app = getToolDefinition('system.app.open'); const write = await routeIncomingRequest('launch the player', { deterministicRoute: { route: 'MODEL', confidence: 0.7 }, tools: [app], needle: needle({ function_calls: [{ name: 'system__app__open', arguments: { app: 'Spotify' } }], confidence: 0.87 }) }); assert.equal(write.route, 'CHATGPT'); assert.equal(write.requiredConfidence, 0.9); });
test('low confidence, refusal, malformed arguments and unknown tools all fail safely to ChatGPT', async () => { const base = { deterministicRoute: { route: 'MODEL', confidence: 0.7 }, tools: [tool] }; assert.equal((await routeIncomingRequest('resource status', { ...base, needle: needle({ function_calls: [{ name: 'system__resources', arguments: {} }], confidence: 0.6 }) })).reason, 'needle_low_confidence'); assert.equal((await routeIncomingRequest('resource status', { ...base, needle: needle({ function_calls: [], confidence: 0.99 }) })).reason, 'needle_refused'); assert.equal((await routeIncomingRequest('resource status', { ...base, needle: needle({ function_calls: [{ name: 'system__resources', arguments: { bad: true } }], confidence: 0.99 }) })).reason, 'needle_invalid_arguments'); assert.equal((await routeIncomingRequest('resource status', { ...base, needle: needle({ function_calls: [{ name: 'nonexistent_tool', arguments: {} }], confidence: 0.99 }) })).reason, 'needle_invalid_tool'); });
test('Needle timeout/unavailability is contained and falls back to ChatGPT', async () => { const decision = await routeIncomingRequest('resource status', { deterministicRoute: { route: 'MODEL', confidence: 0.7 }, tools: [tool], needle: { classifyOrCall: async () => { throw Object.assign(new Error('offline'), { code: 'NEEDLE_UNAVAILABLE' }); } } }); assert.equal(decision.route, 'CHATGPT'); assert.equal(decision.reason, 'needle_failure'); assert.equal(decision.errorCode, 'NEEDLE_UNAVAILABLE'); });
test('reasoning, multi-step and unresolved-context requests bypass Needle', () => { for (const request of ['why is my laptop slow?', 'analyse my RAM usage', 'fix this coding error', 'plan my work for today', 'open that']) assert.equal(requestComplexity(request).complex, true, request); });
