import { copyFile, mkdir, readFile, readdir, realpath, rename, rmdir, stat, unlink, writeFile } from 'node:fs/promises';
import crypto from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const fileWorkspaceRoot=path.resolve(fileURLToPath(new URL('..',import.meta.url)));
const realRootPromise=realpath(fileWorkspaceRoot);
const protectedRoots=new Set(['.git','node_modules','server/data','dist','release']);
function failure(code,message){return Object.assign(new Error(message),{code});}
function relative(file){return path.relative(fileWorkspaceRoot,file).replaceAll('\\','/');}
function lexical(input='.') {const candidate=path.resolve(fileWorkspaceRoot,String(input));if(candidate!==fileWorkspaceRoot&&!candidate.startsWith(`${fileWorkspaceRoot}${path.sep}`))throw failure('PERMISSION_DENIED','Path is outside the JARVIS workspace.');return candidate;}
function protectedPath(candidate){const value=relative(candidate).toLowerCase();return [...protectedRoots].some(root=>value===root||value.startsWith(`${root}/`))||/^\.env(?:\.|$)/i.test(value);}
async function existing(input){const root=await realRootPromise,candidate=lexical(input),actual=await realpath(candidate);if(actual!==root&&!actual.startsWith(`${root}${path.sep}`))throw failure('PERMISSION_DENIED','Resolved path escapes the JARVIS workspace.');return actual;}
async function writable(input){const candidate=lexical(input);if(candidate===fileWorkspaceRoot||protectedPath(candidate))throw failure('PERMISSION_DENIED','This protected project path cannot be mutated by a file tool.');const parent=await existing(path.relative(fileWorkspaceRoot,path.dirname(candidate)));const root=await realRootPromise;if(parent!==root&&!parent.startsWith(`${root}${path.sep}`))throw failure('PERMISSION_DENIED','Destination parent escapes the workspace.');return candidate;}
async function hash(file){const content=await readFile(file);return{bytes:content.length,sha256:crypto.createHash('sha256').update(content).digest('hex')};}

async function walk(current,query,results,limits){if(results.length>=limits.maxResults||limits.visited>=limits.maxFiles)return;for(const entry of await readdir(current,{withFileTypes:true})){if(results.length>=limits.maxResults||limits.visited>=limits.maxFiles)return;if(entry.name.startsWith('.')||['node_modules','dist','release'].includes(entry.name))continue;const file=path.join(current,entry.name);if(entry.isSymbolicLink())continue;if(entry.isDirectory()){await walk(file,query,results,limits);continue;}limits.visited++;let match=entry.name.toLowerCase().includes(query);let preview='';if(!match){const info=await stat(file);if(info.size<=1_000_000){try{const content=await readFile(file,'utf8');const at=content.toLowerCase().indexOf(query);if(at>=0){match=true;preview=content.slice(Math.max(0,at-80),Math.min(content.length,at+query.length+160));}}catch{}}}if(match)results.push({path:relative(file),preview});}}

export async function fileTool(action,args={}){
 if(action==='list'){const directory=await existing(args.path||'.'),info=await stat(directory);if(!info.isDirectory())throw failure('INVALID_ARGUMENTS','List target is not a directory.');const entries=[];for(const entry of await readdir(directory,{withFileTypes:true})){if(entry.name.startsWith('.'))continue;entries.push({name:entry.name,path:relative(path.join(directory,entry.name)),type:entry.isDirectory()?'directory':entry.isSymbolicLink()?'symlink':'file'});}return{path:relative(directory)||'.',entries,verified:true};}
 if(action==='search'){const directory=await existing(args.path||'.'),results=[];const query=String(args.query||'').trim().toLowerCase();if(!query)throw failure('INVALID_ARGUMENTS','Search query is required.');await walk(directory,query,results,{maxResults:args.limit||50,maxFiles:5000,visited:0});return{query:args.query,path:relative(directory)||'.',results,verified:true};}
 if(action==='read'){const file=await existing(args.path),info=await stat(file);if(!info.isFile())throw failure('INVALID_ARGUMENTS','Requested path is not a file.');if(info.size>2_000_000)throw failure('INVALID_ARGUMENTS','File exceeds the 2 MB text-read limit.');return{path:relative(file),content:await readFile(file,'utf8'),bytes:info.size,verified:true};}
 if(action==='create'||action==='write'){const file=await writable(args.path);await writeFile(file,String(args.content??''),{encoding:'utf8',flag:action==='create'?'wx':'w'});return{path:relative(file),...(await hash(file)),verified:true};}
 if(action==='move'||action==='rename'){const source=await existing(args.path),destination=await writable(args.destination);await rename(source,destination);let sourceAbsent=false;try{await stat(source);}catch(error){sourceAbsent=error.code==='ENOENT';}return{path:relative(destination),source:relative(source),sourceAbsent,verified:sourceAbsent};}
 if(action==='copy'){const source=await existing(args.path),destination=await writable(args.destination);if(!(await stat(source)).isFile())throw failure('INVALID_ARGUMENTS','Only files can be copied.');await copyFile(source,destination,1);return{path:relative(destination),source:relative(source),...(await hash(destination)),verified:true};}
 if(action==='delete'){const target=await writable(args.path),info=await stat(target);if(info.isDirectory())await rmdir(target);else await unlink(target);let absent=false;try{await stat(target);}catch(error){absent=error.code==='ENOENT';}return{deletedPath:relative(target),verified:absent};}
 if(action==='mkdir'){const target=lexical(args.path);if(target===fileWorkspaceRoot||protectedPath(target))throw failure('PERMISSION_DENIED','This protected project path cannot be created.');const parent=await existing(path.relative(fileWorkspaceRoot,path.dirname(target)));await mkdir(path.join(parent,path.basename(target)));return{path:relative(target),verified:Boolean(await stat(target))};}
 throw failure('INVALID_ARGUMENTS',`Unsupported file action: ${action}`);
}
