import { chromium } from 'playwright-core';
import { mkdir } from 'node:fs/promises';
import { spawn } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ToolRuntimeError } from './toolErrors.js';
import { HeadlessModelTransport, drainDomStream, emitTextDelta, installDomStream, stopDomStream } from './headlessModelTransport.js';
import { findBrowserExecutable } from './platform/browserExecutable.js';
import { dataDirectory } from './platform/paths.js';

const projectRoot = path.resolve(fileURLToPath(new URL('..', import.meta.url)));
const defaultProfile = path.join(dataDirectory(projectRoot), 'gemini-browser-profile');

export const GEMINI_SELECTORS = Object.freeze({
  composer: ['div[contenteditable="true"][aria-label*="prompt" i]', 'rich-textarea div[contenteditable="true"]', '.ql-editor[contenteditable="true"]', 'textarea[aria-label*="prompt" i]'],
  assistant: ['message-content', '[data-test-id="response-content"]', '.model-response-text', 'model-response'],
  submit: ['button[aria-label*="Send" i]', 'button[data-test-id="send-button"]'],
  stop: ['button[aria-label*="Stop" i]', 'button[data-test-id="stop-button"]'],
});

const geminiError = (code, message, options = {}) => new ToolRuntimeError(code, message, options);
async function firstVisible(page, selectors, timeout = 1000) { for (const selector of selectors) { const locator = page.locator(selector).last(); try { await locator.waitFor({ state: 'visible', timeout }); return locator; } catch {} } return null; }
async function responseTexts(page) { for (const selector of GEMINI_SELECTORS.assistant) { const values = await page.locator(selector).allInnerTexts().catch(() => []); if (values.length) return values.map((value) => value.trim()).filter(Boolean); } return []; }

export class PlaywrightGeminiTransport extends HeadlessModelTransport {
  constructor(options = {}) { super(); this.options = options; this.profileDir = path.resolve(options.profileDir || process.env.JARVIS_GEMINI_PROFILE_DIR || defaultProfile); this.headless = options.headless ?? /^true$/i.test(process.env.JARVIS_GEMINI_HEADLESS || 'true'); this.timeoutMs = Math.max(10_000, Number(options.timeoutMs || process.env.JARVIS_GEMINI_TIMEOUT_MS || 120_000)); this.context = null; this.page = null; this.status = 'STOPPED'; this.sessionUrl = null; this.lastError = null; this.launchHeadless = null; this.loginProcess = null; this.queue = Promise.resolve(); }
  async start(options = {}) { const desired = options.headed === true ? false : this.headless; if (this.context && this.launchHeadless !== desired) await this.close(); if (this.context) return this.health(); this.status = 'STARTING'; try { await mkdir(this.profileDir, { recursive: true }); this.context = await chromium.launchPersistentContext(this.profileDir, { executablePath: this.options.executablePath || await findBrowserExecutable(), headless: desired, viewport: null, args: ['--no-first-run', '--no-default-browser-check'] }); this.launchHeadless = desired; this.context.on('close', () => { this.context = null; this.page = null; this.status = 'STOPPED'; }); this.page = this.context.pages().find((page) => page.url().includes('gemini.google.com')) || this.context.pages()[0] || await this.context.newPage(); this.status = 'READY'; this.lastError = null; return this.health(); } catch (error) { this.status = 'FAILED'; this.lastError = error.message; throw geminiError('GEMINI_WEB_UNAVAILABLE', `Gemini browser could not start: ${error.message}`, { retryable: true }); } }
  async ensurePage(sessionUrl, options = {}) { await this.start(); if (!this.page || this.page.isClosed()) this.page = await this.context.newPage(); if (options.newSession) this.sessionUrl = null; const wanted = options.newSession ? 'https://gemini.google.com/app' : sessionUrl || this.sessionUrl || 'https://gemini.google.com/app'; if (!this.page.url().includes('gemini.google.com') || options.newSession || (sessionUrl && this.page.url() !== sessionUrl)) await this.page.goto(wanted, { waitUntil: 'domcontentloaded', timeout: Math.min(45_000, this.timeoutMs) }); const composer = await firstVisible(this.page, GEMINI_SELECTORS.composer, 6000); if (!composer) { const body = await this.page.locator('body').innerText({ timeout: 3000 }).catch(() => ''); if (/sign in|choose an account|use your google account/i.test(body)) { this.status = 'AUTH_REQUIRED'; throw geminiError('GEMINI_LOGIN_REQUIRED', 'Gemini login is required. Open the Gemini login from Settings and sign in manually.'); } throw geminiError('GEMINI_UI_CHANGED', 'The Gemini prompt composer could not be located.'); } return { page: this.page, composer }; }
  async send(message, options = {}) { let release; const prior = this.queue; this.queue = new Promise((resolve) => { release = resolve; }); await prior; try { this.status = 'BUSY'; const { page, composer } = await this.ensurePage(options.sessionUrl, options); const before = await responseTexts(page); await installDomStream(page, GEMINI_SELECTORS.assistant); await composer.fill(String(message)); const submit = await firstVisible(page, GEMINI_SELECTORS.submit, 1200); if (submit) await submit.click(); else await composer.press('Enter'); const deadline = Date.now() + this.timeoutMs; let last = ''; let streamed = ''; let stableSince = 0; let sawNew = false; while (Date.now() < deadline) { if (options.signal?.aborted) { await this.cancel(); throw geminiError('EXECUTION_CANCELLED', 'Gemini generation was cancelled.'); } const current = await responseTexts(page); const snapshots = await drainDomStream(page); const latest = snapshots.at(-1) || current.at(-1) || ''; if (current.length > before.length || (latest && latest !== before.at(-1))) sawNew = true; const stopping = Boolean(await firstVisible(page, GEMINI_SELECTORS.stop, 120).catch(() => null)); if (sawNew && latest) { streamed = emitTextDelta(streamed, latest, options.onDelta); if (latest === last) stableSince ||= Date.now(); else { last = latest; stableSince = Date.now(); } if (!stopping && Date.now() - stableSince >= 650) { this.sessionUrl = page.url().includes('/app/') ? page.url() : this.sessionUrl; this.status = 'READY'; this.lastError = null; await stopDomStream(page); return { text: latest, sessionUrl: this.sessionUrl || page.url(), partial: false }; } } const body = await page.locator('body').innerText({ timeout: 800 }).catch(() => ''); if (/too many requests|rate limit|try again later|capacity/i.test(body)) throw geminiError('GEMINI_RATE_LIMITED', 'Gemini Web is currently rate limited.', { retryable: true }); await page.waitForTimeout(200); } throw geminiError('GEMINI_TIMEOUT', sawNew ? 'Gemini generation did not finish before the timeout.' : 'Gemini did not produce a response.', { retryable: true, details: { partial: sawNew ? last : null } }); } catch (error) { this.lastError = error.message; this.status = error.code === 'GEMINI_LOGIN_REQUIRED' ? 'AUTH_REQUIRED' : error.code === 'EXECUTION_CANCELLED' ? 'READY' : 'FAILED'; if (error instanceof ToolRuntimeError) throw error; throw geminiError('GEMINI_WEB_UNAVAILABLE', `Gemini Web request failed: ${error.message}`, { retryable: true }); } finally { if (this.page && !this.page.isClosed()) await stopDomStream(this.page); release(); } }
  async cancel() { if (!this.page || this.page.isClosed()) return { cancelled: false }; const stop = await firstVisible(this.page, GEMINI_SELECTORS.stop, 300); if (stop) { await stop.click().catch(() => {}); this.status = 'READY'; return { cancelled: true }; } return { cancelled: false }; }
  async openLogin() { if (this.loginProcess && this.loginProcess.exitCode === null) return this.health(); await this.close(); await mkdir(this.profileDir, { recursive: true }); const child = spawn(this.options.executablePath || await findBrowserExecutable(), [`--user-data-dir=${this.profileDir}`, '--no-first-run', '--no-default-browser-check', '--new-window', 'https://gemini.google.com/app'], { stdio: 'ignore', windowsHide: false }); await new Promise((resolve, reject) => { child.once('spawn', resolve); child.once('error', reject); }); this.loginProcess = child; child.once('exit', () => { this.loginProcess = null; }); child.unref(); this.status = 'AUTH_REQUIRED'; return this.health(); }
  async verifyLogin() { if (this.loginProcess && this.loginProcess.exitCode === null) throw geminiError('GEMINI_SESSION_BUSY', 'Close the Gemini login browser before verification.'); await this.start(); await this.ensurePage(this.sessionUrl); this.status = 'READY'; return this.health(); }
  async reset() { await this.start(); this.sessionUrl = null; if (!this.page || this.page.isClosed()) this.page = await this.context.newPage(); await this.page.goto('https://gemini.google.com/app', { waitUntil: 'domcontentloaded', timeout: Math.min(45_000, this.timeoutMs) }); return this.health(); }
  async health() { if (this.loginProcess && this.loginProcess.exitCode === null) return { status: 'AUTH_REQUIRED', browser: 'LOGIN_WINDOW', authenticated: false, mode: 'HEADED', session: 'NONE', lastError: this.lastError }; const running = Boolean(this.context && this.page && !this.page.isClosed()); const authenticated = running && this.page.url().includes('gemini.google.com') ? Boolean(await firstVisible(this.page, GEMINI_SELECTORS.composer, 600).catch(() => null)) : false; return { status: this.status, browser: running ? 'RUNNING' : 'STOPPED', authenticated, mode: running ? (this.launchHeadless ? 'HEADLESS' : 'HEADED') : (this.headless ? 'HEADLESS' : 'HEADED'), session: this.sessionUrl ? 'ACTIVE' : 'NONE', sessionUrl: this.sessionUrl, lastError: this.lastError }; }
  async diagnose() { if (!this.page || this.page.isClosed()) return { browser: 'STOPPED', url: null, composerCandidates: [] }; return { browser: 'RUNNING', url: this.page.url(), title: await this.page.title().catch(() => ''), composerCandidates: await this.page.locator('textarea,[contenteditable="true"],[role="textbox"]').evaluateAll((nodes) => nodes.slice(0, 12).map((node) => ({ tag: node.tagName.toLowerCase(), label: node.getAttribute('aria-label'), visible: Boolean(node.getClientRects().length) }))).catch(() => []) }; }
  async close() { const context = this.context; this.context = null; this.page = null; this.launchHeadless = null; this.status = 'STOPPED'; if (context) await context.close().catch(() => {}); }
}

let shared;
export function geminiWebTransport() { shared ||= new PlaywrightGeminiTransport(); return shared; }
export async function closeGeminiWebTransport() { if (shared) await shared.close(); shared = null; }
