import crypto from 'node:crypto';
import { ToolRuntimeError } from './toolErrors.js';

const pendingSecrets = new Map();
const MAX_CLOCK_SKEW_MS = 120_000;
function masterKey() { const value=String(process.env.PHONE_BRIDGE_MASTER_KEY||'');if(value.length<32)throw new ToolRuntimeError('CONFIGURATION_MISSING','PHONE_BRIDGE_MASTER_KEY must contain at least 32 characters');return crypto.createHash('sha256').update(value).digest(); }
function hmac(key,value){return crypto.createHmac('sha256',key).update(value).digest('base64url');}
function equal(left,right){const a=Buffer.from(String(left));const b=Buffer.from(String(right));return a.length===b.length&&crypto.timingSafeEqual(a,b);}
function deriveDeviceToken(device){return hmac(masterKey(),`jarvis-phone:${device.id}:${device.salt}`);}
function aesKey(secret){return crypto.createHash('sha256').update(secret).digest();}

export function encryptEnvelope(secret,payload){const iv=crypto.randomBytes(12);const cipher=crypto.createCipheriv('aes-256-gcm',aesKey(secret),iv);const encrypted=Buffer.concat([cipher.update(JSON.stringify(payload),'utf8'),cipher.final()]);return{version:1,iv:iv.toString('base64url'),ciphertext:encrypted.toString('base64url'),tag:cipher.getAuthTag().toString('base64url')};}
export function decryptEnvelope(secret,envelope){try{const decipher=crypto.createDecipheriv('aes-256-gcm',aesKey(secret),Buffer.from(envelope.iv,'base64url'));decipher.setAuthTag(Buffer.from(envelope.tag,'base64url'));return JSON.parse(Buffer.concat([decipher.update(Buffer.from(envelope.ciphertext,'base64url')),decipher.final()]).toString('utf8'));}catch{throw new ToolRuntimeError('AUTHENTICATION_REQUIRED','Invalid encrypted phone-bridge envelope');}}

export function phoneBridgeStatus(state){const configured=String(process.env.PHONE_BRIDGE_MASTER_KEY||'').length>=32;return{configured,transport:'signed-encrypted-http-polling',mobileCompanionRequired:true,devices:(state.phoneBridge?.devices||[]).map(({salt,...device})=>device),pendingCommands:(state.phoneBridge?.commands||[]).filter(item=>item.status==='queued').length};}

export function beginPhonePairing(state,input={}){masterKey();const pairingId=`pair-${crypto.randomUUID()}`;const secret=crypto.randomBytes(24).toString('base64url');const expiresAt=Date.now()+300_000;pendingSecrets.set(pairingId,{secret,expiresAt});state.phoneBridge??={devices:[],pairings:[],commands:[],receipts:[]};state.phoneBridge.pairings=[{id:pairingId,secretHash:hmac(masterKey(),secret),expiresAt:new Date(expiresAt).toISOString(),label:String(input.label||'Phone companion'),status:'pending'},...(state.phoneBridge.pairings||[])].slice(0,20);return{pairingId,pairingSecret:secret,expiresAt:new Date(expiresAt).toISOString(),warning:'Transfer this one-time secret directly to the trusted phone companion. It is not stored in plaintext.'};}

export function completePhonePairing(state,input={}){masterKey();const pending=pendingSecrets.get(String(input.pairingId||''));const pairing=(state.phoneBridge?.pairings||[]).find(item=>item.id===input.pairingId);if(!pending||!pairing||pending.expiresAt<Date.now()||pairing.status!=='pending')throw new ToolRuntimeError('AUTHENTICATION_REQUIRED','Phone pairing is invalid or expired');const deviceId=String(input.deviceId||'').trim();const nonce=String(input.clientNonce||'').trim();if(!/^[A-Za-z0-9._-]{3,100}$/.test(deviceId)||nonce.length<16)throw new ToolRuntimeError('INVALID_ARGUMENTS','A valid deviceId and clientNonce are required');const expected=hmac(pending.secret,`pair:${pairing.id}:${deviceId}:${nonce}`);if(!equal(expected,input.proof))throw new ToolRuntimeError('AUTHENTICATION_REQUIRED','Phone pairing proof is invalid');if((state.phoneBridge.devices||[]).some(item=>item.id===deviceId))throw new ToolRuntimeError('INVALID_ARGUMENTS','This device ID is already paired');const device={id:deviceId,name:String(input.name||deviceId).slice(0,100),salt:crypto.randomBytes(24).toString('base64url'),permissions:Array.isArray(input.permissions)?input.permissions.map(String).slice(0,20):[],pairedAt:new Date().toISOString(),lastSeenAt:null,revokedAt:null};state.phoneBridge.devices.push(device);pairing.status='completed';pairing.completedAt=new Date().toISOString();pendingSecrets.delete(pairing.id);const token=deriveDeviceToken(device);return{device:{...device,salt:undefined},credentials:encryptEnvelope(pending.secret,{deviceId,token}),transport:'AES-256-GCM payloads plus HMAC-SHA256 request authentication'};}

export function authenticatePhoneEnvelope(state,input={},purpose='request'){masterKey();const device=(state.phoneBridge?.devices||[]).find(item=>item.id===input.deviceId&&!item.revokedAt);if(!device)throw new ToolRuntimeError('AUTHENTICATION_REQUIRED','Unknown or revoked phone device');const timestamp=Number(input.timestamp);const nonce=String(input.nonce||'');if(!Number.isFinite(timestamp)||Math.abs(Date.now()-timestamp)>MAX_CLOCK_SKEW_MS||nonce.length<16)throw new ToolRuntimeError('AUTHENTICATION_REQUIRED','Phone request timestamp or nonce is invalid');state.phoneBridge.receipts??=[];if(state.phoneBridge.receipts.some(item=>item.deviceId===device.id&&item.nonce===nonce))throw new ToolRuntimeError('AUTHENTICATION_REQUIRED','Phone request replay rejected');const token=deriveDeviceToken(device);const expected=hmac(token,`${purpose}:${device.id}:${timestamp}:${nonce}:${input.iv}:${input.ciphertext}:${input.tag}`);if(!equal(expected,input.signature))throw new ToolRuntimeError('AUTHENTICATION_REQUIRED','Phone request signature is invalid');const payload=decryptEnvelope(token,input);state.phoneBridge.receipts.unshift({deviceId:device.id,nonce,at:new Date().toISOString()});state.phoneBridge.receipts=state.phoneBridge.receipts.slice(0,1000);device.lastSeenAt=new Date().toISOString();return{device,payload,token};}

export function phoneTool(action,args,state){state.phoneBridge??={devices:[],pairings:[],commands:[],receipts:[]};if(action==='status')return{...phoneBridgeStatus(state),verified:true};if(action==='devices')return{devices:phoneBridgeStatus(state).devices,verified:true};if(action==='command'){masterKey();const device=state.phoneBridge.devices.find(item=>item.id===args.deviceId&&!item.revokedAt);if(!device)throw new ToolRuntimeError('CONNECTION_UNAVAILABLE','The selected phone is not paired or has been revoked');if(!device.permissions.includes(args.capability))throw new ToolRuntimeError('PERMISSION_DENIED',`Phone capability ${args.capability} was not granted during pairing`);const command={id:`phone-command-${crypto.randomUUID()}`,deviceId:device.id,capability:args.capability,action:args.action,payload:args.payload||{},status:'queued',createdAt:new Date().toISOString(),acknowledgedAt:null,result:null};state.phoneBridge.commands.unshift(command);state.phoneBridge.commands=state.phoneBridge.commands.slice(0,500);return{command:{...command,payload:undefined},verified:true,executionState:'QUEUED_FOR_DEVICE',warning:'The command is queued and has not been executed by the phone yet.'};}throw new ToolRuntimeError('TOOL_NOT_FOUND',`Unsupported phone action: ${action}`);}
export function pollPhoneCommands(state,authenticated){const commands=(state.phoneBridge?.commands||[]).filter(item=>item.deviceId===authenticated.device.id&&item.status==='queued').slice(0,20);return encryptEnvelope(authenticated.token,{commands});}
export function acceptPhoneEvent(state,authenticated){const event=authenticated.payload;if(event.commandId){const command=(state.phoneBridge?.commands||[]).find(item=>item.id===event.commandId&&item.deviceId===authenticated.device.id);if(command){command.status=event.status==='completed'?'completed':'failed';command.acknowledgedAt=new Date().toISOString();command.result=event.result||null;}}return{accepted:true,deviceId:authenticated.device.id,event};}
