const objectSchema = (properties = {}, required = []) => ({ type: 'object', properties, required, additionalProperties: false });
const outputSchema = { type: 'object', required: ['ok', 'toolId', 'data'], properties: { ok: { type: 'boolean' }, toolId: { type: 'string' } }, additionalProperties: true };

const tools = [
  { id: 'project.inspect', name: 'Project inspection', description: 'Inspect the current repository structure and project metadata.', module: 'development', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 10000, enabled: true, inputSchema: objectSchema() },
  { id: 'projects.status', name: 'Project status', description: 'Read real git and package status for configured local projects.', module: 'projects', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 10000, enabled: true, inputSchema: objectSchema() },
  { id: 'models.list', name: 'Available model routes', description: 'List logical models, configured provider pools, and credential readiness.', module: 'models', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 5000, enabled: true, inputSchema: objectSchema() },
  { id: 'mcp.servers', name: 'MCP server discovery', description: 'List configured MCP servers and discover their declared tools without executing them.', module: 'integrations', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 10000, enabled: true, inputSchema: objectSchema() },
  { id: 'mcp.call', name: 'Call approved MCP tool', description: 'Call a discovered MCP tool only after approval bound to the server, tool and exact arguments.', module: 'integrations', riskLevel: 'EXTERNAL_ACTION', sideEffects: true, reversible: false, timeout: 15000, enabled: true, requiresApproval: true, inputSchema: objectSchema({ server: { type: 'string' }, tool: { type: 'string' }, arguments: { type: 'object' } }, ['server', 'tool']) },
  { id: 'files.read', name: 'Read project files', description: 'Read a UTF-8 file located inside the JARVIS project workspace.', module: 'files', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 10000, enabled: true, inputSchema: objectSchema({ path: { type: 'string', description: 'Workspace-relative file path.' } }, ['path']) },
  { id: 'tasks.list', name: 'List tasks', description: 'List the user\'s real persisted JARVIS tasks and their current state.', module: 'productivity', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 10000, enabled: true, inputSchema: objectSchema() },
  { id: 'tasks.manage', name: 'Manage tasks', description: 'Create or update a persisted JARVIS task.', module: 'productivity', riskLevel: 'LOW_RISK_WRITE', sideEffects: true, reversible: true, timeout: 10000, enabled: true, inputSchema: objectSchema({ id: { type: 'string' }, title: { type: 'string', minLength: 1, maxLength: 300 }, status: { type: 'string', enum: ['pending', 'active', 'completed', 'cancelled'] } }) },
  { id: 'memory.search', name: 'Search memory', description: 'Retrieve relevant approved project and durable memory records.', module: 'memory', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 10000, enabled: true, inputSchema: objectSchema({ query: { type: 'string' } }, ['query']) },
  { id: 'runtime.telemetry', name: 'Runtime telemetry', description: 'Read the active provider, selected model, usage, uptime, and latency.', module: 'system', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 5000, enabled: true, inputSchema: objectSchema() },
  { id: 'diagnostics', name: 'System diagnostics', description: 'Check JARVIS service health and integration readiness.', module: 'system', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 5000, enabled: true, inputSchema: objectSchema() },
  { id: 'browser.open', name: 'Open web page', description: 'Open a safe HTTP or HTTPS URL in the user interface.', module: 'computer', riskLevel: 'LOW_RISK_WRITE', sideEffects: true, reversible: true, timeout: 5000, enabled: true, inputSchema: objectSchema({ url: { type: 'string' } }, ['url']) },
  { id: 'browser.navigate', name: 'Navigate browser', description: 'Navigate with the managed browser; Lightpanda is primary and Firefox handles visual fallback.', module: 'browser', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 45000, enabled: true, inputSchema: objectSchema({ url: { type: 'string' }, mode: { type: 'string', enum: ['normal', 'visual'] } }, ['url']) },
  { id: 'browser.click', name: 'Click browser element', description: 'Click a CSS selector in the managed browser.', module: 'browser', riskLevel: 'LOW_RISK_WRITE', sideEffects: true, reversible: false, timeout: 30000, enabled: true, inputSchema: objectSchema({ selector: { type: 'string' }, mode: { type: 'string', enum: ['normal', 'visual'] } }, ['selector']) },
  { id: 'browser.type', name: 'Type into browser field', description: 'Fill a CSS selector in the managed browser.', module: 'browser', riskLevel: 'LOW_RISK_WRITE', sideEffects: true, reversible: true, timeout: 30000, enabled: true, inputSchema: objectSchema({ selector: { type: 'string' }, text: { type: 'string' } }, ['selector', 'text']) },
  { id: 'browser.read', name: 'Read browser page', description: 'Read page title, text, and links.', module: 'browser', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 20000, enabled: true, inputSchema: objectSchema() },
  { id: 'browser.content', name: 'Read browser HTML', description: 'Read bounded page HTML.', module: 'browser', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 20000, enabled: true, inputSchema: objectSchema() },
  { id: 'browser.accessibility', name: 'Read browser controls', description: 'Read accessible page controls.', module: 'browser', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 20000, enabled: true, inputSchema: objectSchema() },
  { id: 'browser.screenshot', name: 'Capture browser page', description: 'Capture a visual Firefox screenshot.', module: 'browser', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 45000, enabled: true, inputSchema: objectSchema() },
  { id: 'browser.wait', name: 'Wait for browser element', description: 'Wait for a CSS selector.', module: 'browser', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 30000, enabled: true, inputSchema: objectSchema({ selector: { type: 'string' }, timeout: { type: 'integer', minimum: 100, maximum: 25000 } }, ['selector']) },
  { id: 'browser.evaluate', name: 'Evaluate page JavaScript', description: 'Run approved JavaScript in the browser page.', module: 'browser', riskLevel: 'PROJECT_EXECUTION', sideEffects: true, reversible: false, timeout: 30000, enabled: true, requiresApproval: true, inputSchema: objectSchema({ code: { type: 'string' } }, ['code']) },
  { id: 'browser.status', name: 'Browser status', description: 'Read managed browser engine, URL, and handoff state.', module: 'browser', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 5000, enabled: true, inputSchema: objectSchema() },
  { id: 'browser.handoff', name: 'Open verification browser', description: 'Bring the headed Firefox verification page forward.', module: 'browser', riskLevel: 'LOW_RISK_WRITE', sideEffects: true, reversible: true, timeout: 30000, enabled: true, inputSchema: objectSchema() },
  { id: 'browser.resume', name: 'Resume browser task', description: 'Resume the same browser session after human verification.', module: 'browser', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 15000, enabled: true, inputSchema: objectSchema() },
  { id: 'browser.close', name: 'Close managed browser', description: 'Close active managed browser engines.', module: 'browser', riskLevel: 'LOW_RISK_WRITE', sideEffects: true, reversible: true, timeout: 15000, enabled: true, inputSchema: objectSchema() },
  { id: 'apps.list', name: 'List installed desktop applications', description: 'Discover launchable applications in the current operating system.', module: 'computer', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 10000, enabled: true, inputSchema: objectSchema() },
  { id: 'computer.capabilities', name: 'Desktop capability status', description: 'Report actual platform provider availability and unsupported desktop controls.', module: 'computer', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 5000, enabled: true, inputSchema: objectSchema() },
  { id: 'computer.keypress', name: 'Press desktop keys', description: 'Send one approved key combination to the focused desktop application through the consent-based portal.', module: 'computer', riskLevel: 'PROJECT_EXECUTION', sideEffects: true, reversible: false, timeout: 60000, enabled: false, requiresApproval: true, inputSchema: objectSchema({ keys: { type: 'string', minLength: 1, maxLength: 60 } }, ['keys']) },
  { id: 'computer.type', name: 'Type desktop text', description: 'Type exact approved text into the focused desktop application through the consent-based portal.', module: 'computer', riskLevel: 'PROJECT_EXECUTION', sideEffects: true, reversible: false, timeout: 60000, enabled: false, requiresApproval: true, inputSchema: objectSchema({ text: { type: 'string', minLength: 1, maxLength: 500 } }, ['text']) },
  { id: 'screen.capture', name: 'Capture desktop screen', description: 'Request a real desktop screenshot through the session portal; may require user consent.', module: 'computer', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 50000, enabled: true, inputSchema: objectSchema({ target: { type: 'string', enum: ['desktop'] } }) },
  { id: 'apps.open', name: 'Open desktop application', description: 'Launch one unambiguously resolved installed application.', module: 'computer', riskLevel: 'LOW_RISK_WRITE', sideEffects: true, reversible: true, timeout: 15000, enabled: true, inputSchema: objectSchema({ name: { type: 'string', minLength: 1, maxLength: 120 } }, ['name']) },
  { id: 'audio.get_volume', name: 'Read system volume', description: 'Read the actual default output volume and mute state.', module: 'computer', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 5000, enabled: true, inputSchema: objectSchema() },
  { id: 'audio.set_volume', name: 'Set system volume', description: 'Set and verify default output volume.', module: 'computer', riskLevel: 'LOW_RISK_WRITE', sideEffects: true, reversible: true, timeout: 10000, enabled: true, inputSchema: objectSchema({ volume: { type: 'integer', minimum: 0, maximum: 100 } }, ['volume']) },
  { id: 'audio.volume_up', name: 'Increase system volume', description: 'Increase and verify default output volume.', module: 'computer', riskLevel: 'LOW_RISK_WRITE', sideEffects: true, reversible: true, timeout: 10000, enabled: true, inputSchema: objectSchema({ step: { type: 'integer', minimum: 1, maximum: 25 } }) },
  { id: 'audio.volume_down', name: 'Decrease system volume', description: 'Decrease and verify default output volume.', module: 'computer', riskLevel: 'LOW_RISK_WRITE', sideEffects: true, reversible: true, timeout: 10000, enabled: true, inputSchema: objectSchema({ step: { type: 'integer', minimum: 1, maximum: 25 } }) },
  { id: 'audio.mute', name: 'Mute system audio', description: 'Mute and verify default output.', module: 'computer', riskLevel: 'LOW_RISK_WRITE', sideEffects: true, reversible: true, timeout: 10000, enabled: true, inputSchema: objectSchema() },
  { id: 'audio.unmute', name: 'Unmute system audio', description: 'Unmute and verify default output.', module: 'computer', riskLevel: 'LOW_RISK_WRITE', sideEffects: true, reversible: true, timeout: 10000, enabled: true, inputSchema: objectSchema() },
  { id: 'clipboard.read', name: 'Read clipboard', description: 'Read current clipboard text from the active desktop session.', module: 'computer', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 5000, enabled: true, inputSchema: objectSchema() },
  { id: 'clipboard.write', name: 'Write clipboard', description: 'Write text to the current desktop clipboard and verify it.', module: 'computer', riskLevel: 'LOW_RISK_WRITE', sideEffects: true, reversible: true, timeout: 10000, enabled: true, inputSchema: objectSchema({ text: { type: 'string', maxLength: 1000000 } }, ['text']) },
  { id: 'media.status', name: 'Read desktop media player', description: 'Read actual MPRIS player state and track metadata.', module: 'computer', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 10000, enabled: true, inputSchema: objectSchema({ player: { type: 'string' } }) },
  ...['play', 'pause', 'toggle', 'next', 'previous'].map((action) => ({ id: `media.${action}`, name: `${action} desktop media`, description: `Control one unambiguously selected MPRIS player and verify ${action}.`, module: 'computer', riskLevel: 'LOW_RISK_WRITE', sideEffects: true, reversible: true, timeout: 10000, enabled: true, inputSchema: objectSchema({ player: { type: 'string' } }) })),
  { id: 'gmail.latest', name: 'Read latest Gmail messages', description: 'Fetch recent inbox email through the connected Gmail account.', module: 'communication', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 30000, enabled: false, requires: 'COMPOSIO_API_KEY', inputSchema: objectSchema({ limit: { type: 'integer', minimum: 1, maximum: 20 } }) },
  { id: 'calendar.create', name: 'Create calendar event', description: 'Create an event through the configured calendar provider after exact approval.', module: 'productivity', riskLevel: 'EXTERNAL_ACTION', sideEffects: true, reversible: false, timeout: 15000, enabled: false, requires: 'CALENDAR_API_URL', requiresApproval: true, inputSchema: objectSchema({ payload: { type: 'object' } }, ['payload']) },
  { id: 'media.generate', name: 'Generate image or video', description: 'Generate an image or video with the configured Gemini media model.', module: 'media', riskLevel: 'EXTERNAL_ACTION', sideEffects: true, reversible: true, timeout: 120000, enabled: false, requires: 'GEMINI_API_KEY', inputSchema: objectSchema({ kind: { type: 'string', enum: ['image', 'video'] }, prompt: { type: 'string' } }, ['kind', 'prompt']) },
  { id: 'command.execute', name: 'Execute a command', description: 'Execute one approved, workspace-contained command without shell operators.', module: 'computer', riskLevel: 'PROJECT_EXECUTION', sideEffects: true, reversible: false, timeout: 30000, enabled: true, requiresApproval: true, inputSchema: objectSchema({ command: { type: 'string' } }, ['command']) },
  { id: 'research.search', name: 'Research web sources', description: 'Search configured web sources and return attributed results.', module: 'research', riskLevel: 'EXTERNAL_ACTION', sideEffects: true, reversible: true, timeout: 15000, enabled: false, requires: 'SEARCH_PROVIDER_URL', inputSchema: objectSchema({ query: { type: 'string' } }, ['query']) },
  { id: 'research.plan', name: 'Grounded research plan', description: 'Collect attributable sources and return an explicit research/media planning state.', module: 'research', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 15000, enabled: false, requires: 'SEARCH_PROVIDER_URL', inputSchema: objectSchema({ topic: { type: 'string' }, media: { type: 'boolean' } }, ['topic']) },
  { id: 'messages.send', name: 'Send messages', description: 'Send a message through a configured provider after approval.', module: 'communication', riskLevel: 'EXTERNAL_ACTION', sideEffects: true, reversible: false, timeout: 15000, enabled: false, requires: 'MESSAGING_TOKEN', requiresApproval: true, inputSchema: objectSchema({ recipient: { type: 'string' }, channel: { type: 'string' }, text: { type: 'string' }, message: { type: 'string' }, assistantAuthored: { type: 'boolean' } }) },
  { id: 'composio.execute', name: 'Execute Composio action', description: 'Execute an action in a connected Composio app; consequential actions require exact approval.', module: 'integrations', riskLevel: 'EXTERNAL_ACTION', sideEffects: true, reversible: false, timeout: 30000, enabled: false, requires: 'COMPOSIO_API_KEY', requiresApproval: true, inputSchema: objectSchema({ toolSlug: { type: 'string' }, arguments: { type: 'object' }, connectedAccountId: { type: 'string' }, userId: { type: 'string' }, version: { type: 'string' }, timeoutMs: { type: 'integer', minimum: 1000, maximum: 30000 } }, ['toolSlug']) },
];

export function listTools() {
  return tools.map((tool) => ({
    ...tool,
    outputSchema,
    ...(tool.id === 'computer.keypress' || tool.id === 'computer.type' ? { enabled: process.platform === 'linux' && process.env.JARVIS_DESKTOP_INPUT === '1' && Boolean(process.env.JARVIS_AUTH_TOKEN) } : tool.id.startsWith('audio.') || tool.id.startsWith('clipboard.') || tool.id === 'screen.capture' || tool.id.startsWith('media.') && tool.id !== 'media.generate' ? { enabled: process.platform === 'linux' } : tool.id === 'messages.send' ? { enabled: Boolean(process.env.MESSAGING_API_URL || process.env.SLACK_WEBHOOK_URL || process.env.SLACK_BOT_TOKEN) } : tool.id === 'calendar.create' ? { enabled: Boolean(process.env.CALENDAR_API_URL || process.env.SLACK_BOT_TOKEN && process.env.SLACK_CHANNEL_ID) } : tool.requires ? { enabled: Boolean(process.env[tool.requires]) } : {}),
  }));
}
export function getTool(id) { return listTools().find((tool) => tool.id === id) || null; }
export function listCapabilities() {
  const current = listTools();
  return [...new Set(current.map((tool) => tool.module))].map((module) => ({ module, tools: current.filter((tool) => tool.module === module).map((tool) => tool.id) }));
}
