const objectSchema = (properties = {}, required = []) => ({ type: 'object', properties, required, additionalProperties: false });

const tools = [
  { id: 'project.inspect', name: 'Project inspection', description: 'Inspect the current repository structure and project metadata.', module: 'development', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 10000, enabled: true, inputSchema: objectSchema() },
  { id: 'projects.status', name: 'Project status', description: 'Read real git and package status for configured local projects.', module: 'projects', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 10000, enabled: true, inputSchema: objectSchema() },
  { id: 'models.list', name: 'Available model routes', description: 'List logical models, configured provider pools, and credential readiness.', module: 'models', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 5000, enabled: true, inputSchema: objectSchema() },
  { id: 'mcp.servers', name: 'MCP server discovery', description: 'List configured MCP servers and discover their declared tools without executing them.', module: 'integrations', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 10000, enabled: true, inputSchema: objectSchema() },
  { id: 'mcp.call', name: 'Call approved MCP tool', description: 'Call a discovered MCP tool only after approval bound to the server, tool and exact arguments.', module: 'integrations', riskLevel: 'EXTERNAL_ACTION', sideEffects: true, reversible: false, timeout: 15000, enabled: true, requiresApproval: true, inputSchema: objectSchema({ server: { type: 'string' }, tool: { type: 'string' }, arguments: { type: 'object' } }, ['server', 'tool']) },
  { id: 'files.read', name: 'Read project files', description: 'Read a UTF-8 file located inside the JARVIS project workspace.', module: 'files', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 10000, enabled: true, inputSchema: objectSchema({ path: { type: 'string', description: 'Workspace-relative file path.' } }, ['path']) },
  { id: 'tasks.list', name: 'List tasks', description: 'List the user\'s real persisted JARVIS tasks and their current state.', module: 'productivity', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 10000, enabled: true, inputSchema: objectSchema() },
  { id: 'tasks.manage', name: 'Manage tasks', description: 'Create or update a persisted JARVIS task.', module: 'productivity', riskLevel: 'LOW_RISK_WRITE', sideEffects: true, reversible: true, timeout: 10000, enabled: true, inputSchema: objectSchema({ title: { type: 'string' }, status: { type: 'string' } }) },
  { id: 'memory.search', name: 'Search memory', description: 'Retrieve relevant approved project and durable memory records.', module: 'memory', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 10000, enabled: true, inputSchema: objectSchema({ query: { type: 'string' } }, ['query']) },
  { id: 'runtime.telemetry', name: 'Runtime telemetry', description: 'Read the active provider, selected model, usage, uptime, and latency.', module: 'system', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 5000, enabled: true, inputSchema: objectSchema() },
  { id: 'diagnostics', name: 'System diagnostics', description: 'Check JARVIS service health and integration readiness.', module: 'system', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 5000, enabled: true, inputSchema: objectSchema() },
  { id: 'browser.open', name: 'Open web page', description: 'Open a safe HTTP or HTTPS URL in the user interface.', module: 'computer', riskLevel: 'LOW_RISK_WRITE', sideEffects: true, reversible: true, timeout: 5000, enabled: true, inputSchema: objectSchema({ url: { type: 'string' } }, ['url']) },
  { id: 'browser.navigate', name: 'Navigate browser', description: 'Navigate with the managed browser; Lightpanda is primary and Firefox handles visual fallback.', module: 'browser', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 45000, enabled: true, inputSchema: objectSchema({ url: { type: 'string' }, mode: { type: 'string', enum: ['normal', 'visual'] } }, ['url']) },
  { id: 'browser.click', name: 'Click browser element', description: 'Click a CSS selector in the managed browser.', module: 'browser', riskLevel: 'LOW_RISK_WRITE', sideEffects: true, reversible: false, timeout: 30000, enabled: true, inputSchema: objectSchema({ selector: { type: 'string' }, mode: { type: 'string', enum: ['normal', 'visual'] } }, ['selector']) },
  { id: 'browser.type', name: 'Type into browser field', description: 'Fill a CSS selector in the managed browser.', module: 'browser', riskLevel: 'LOW_RISK_WRITE', sideEffects: true, reversible: true, timeout: 30000, enabled: true, inputSchema: objectSchema({ selector: { type: 'string' }, text: { type: 'string' } }, ['selector', 'text']) },
  { id: 'browser.read', name: 'Read browser page', description: 'Read page title, text, and links.', module: 'browser', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 20000, enabled: true, inputSchema: objectSchema() },
  { id: 'browser.content', name: 'Read browser HTML', description: 'Read bounded page HTML.', module: 'browser', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 20000, enabled: true, inputSchema: objectSchema() },
  { id: 'browser.accessibility', name: 'Read browser controls', description: 'Read accessible page controls.', module: 'browser', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 20000, enabled: true, inputSchema: objectSchema() },
  { id: 'browser.screenshot', name: 'Capture browser page', description: 'Capture a visual Firefox screenshot.', module: 'browser', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 45000, enabled: true, inputSchema: objectSchema() },
  { id: 'browser.wait', name: 'Wait for browser element', description: 'Wait for a CSS selector.', module: 'browser', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 30000, enabled: true, inputSchema: objectSchema({ selector: { type: 'string' }, timeout: { type: 'integer', minimum: 100, maximum: 25000 } }, ['selector']) },
  { id: 'browser.evaluate', name: 'Evaluate page JavaScript', description: 'Run approved JavaScript in the browser page.', module: 'browser', riskLevel: 'PROJECT_EXECUTION', sideEffects: true, reversible: false, timeout: 30000, enabled: true, requiresApproval: true, inputSchema: objectSchema({ code: { type: 'string' } }, ['code']) },
  { id: 'browser.status', name: 'Browser status', description: 'Read managed browser engine, URL, and handoff state.', module: 'browser', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 5000, enabled: true, inputSchema: objectSchema() },
  { id: 'browser.handoff', name: 'Open verification browser', description: 'Bring the headed Firefox verification page forward.', module: 'browser', riskLevel: 'LOW_RISK_WRITE', sideEffects: true, reversible: true, timeout: 30000, enabled: true, inputSchema: objectSchema() },
  { id: 'browser.resume', name: 'Resume browser task', description: 'Resume the same browser session after human verification.', module: 'browser', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 15000, enabled: true, inputSchema: objectSchema() },
  { id: 'browser.close', name: 'Close managed browser', description: 'Close active managed browser engines.', module: 'browser', riskLevel: 'LOW_RISK_WRITE', sideEffects: true, reversible: true, timeout: 15000, enabled: true, inputSchema: objectSchema() },
  { id: 'apps.list', name: 'List installed desktop applications', description: 'Discover launchable applications in the current operating system.', module: 'computer', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 10000, enabled: true, inputSchema: objectSchema() },
  { id: 'apps.open', name: 'Open desktop application', description: 'Launch one unambiguously resolved installed application.', module: 'computer', riskLevel: 'LOW_RISK_WRITE', sideEffects: true, reversible: true, timeout: 15000, enabled: true, inputSchema: objectSchema({ name: { type: 'string', minLength: 1, maxLength: 120 } }, ['name']) },
  { id: 'gmail.latest', name: 'Read latest Gmail messages', description: 'Fetch recent inbox email through the connected Gmail account.', module: 'communication', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 30000, enabled: false, requires: 'COMPOSIO_API_KEY', inputSchema: objectSchema({ limit: { type: 'integer', minimum: 1, maximum: 20 } }) },
  { id: 'media.generate', name: 'Generate image or video', description: 'Generate an image or video with the configured Gemini media model.', module: 'media', riskLevel: 'EXTERNAL_ACTION', sideEffects: true, reversible: true, timeout: 120000, enabled: false, requires: 'GEMINI_API_KEY', inputSchema: objectSchema({ kind: { type: 'string', enum: ['image', 'video'] }, prompt: { type: 'string' } }, ['kind', 'prompt']) },
  { id: 'command.execute', name: 'Execute a command', description: 'Execute one approved, workspace-contained command without shell operators.', module: 'computer', riskLevel: 'PROJECT_EXECUTION', sideEffects: true, reversible: false, timeout: 30000, enabled: true, requiresApproval: true, inputSchema: objectSchema({ command: { type: 'string' } }, ['command']) },
  { id: 'research.search', name: 'Research web sources', description: 'Search configured web sources and return attributed results.', module: 'research', riskLevel: 'EXTERNAL_ACTION', sideEffects: true, reversible: true, timeout: 15000, enabled: false, requires: 'SEARCH_PROVIDER_URL', inputSchema: objectSchema({ query: { type: 'string' } }, ['query']) },
  { id: 'research.plan', name: 'Grounded research plan', description: 'Collect attributable sources and return an explicit research/media planning state.', module: 'research', riskLevel: 'READ_ONLY', sideEffects: false, reversible: true, timeout: 15000, enabled: false, requires: 'SEARCH_PROVIDER_URL', inputSchema: objectSchema({ topic: { type: 'string' }, media: { type: 'boolean' } }, ['topic']) },
  { id: 'messages.send', name: 'Send messages', description: 'Send a message through a configured provider after approval.', module: 'communication', riskLevel: 'EXTERNAL_ACTION', sideEffects: true, reversible: false, timeout: 15000, enabled: false, requires: 'MESSAGING_TOKEN', requiresApproval: true, inputSchema: objectSchema({ recipient: { type: 'string' }, message: { type: 'string' } }, ['recipient', 'message']) },
  { id: 'composio.execute', name: 'Execute Composio action', description: 'Execute an action in a connected Composio app; consequential actions require exact approval.', module: 'integrations', riskLevel: 'EXTERNAL_ACTION', sideEffects: true, reversible: false, timeout: 30000, enabled: false, requires: 'COMPOSIO_API_KEY', requiresApproval: true, inputSchema: objectSchema({ toolSlug: { type: 'string' }, arguments: { type: 'object' } }, ['toolSlug']) },
];

export function listTools() {
  return tools.map((tool) => ({
    ...tool,
    ...(tool.id === 'messages.send' ? { enabled: Boolean(process.env.MESSAGING_API_URL || process.env.SLACK_WEBHOOK_URL || process.env.SLACK_BOT_TOKEN) } : tool.requires ? { enabled: Boolean(process.env[tool.requires]) } : {}),
  }));
}
export function listCapabilities() {
  const current = listTools();
  return [...new Set(current.map((tool) => tool.module))].map((module) => ({ module, tools: current.filter((tool) => tool.module === module).map((tool) => tool.id) }));
}
