import { useEffect, useState } from 'react';
import useAppearance, { DEFAULTS, FONT_OPTIONS, THEME_PRESETS, saveCustomFont } from '../hooks/useAppearance.js';

const stateLabel = { not_verified: 'Not verified', valid: 'Valid ✓', invalid: 'Invalid ✕', network_error: 'Network error', provider_error: 'Provider error' };

export function CredentialManagerPanel() {
  const [providers, setProviders] = useState([]); const [drafts, setDrafts] = useState({}); const [shown, setShown] = useState({}); const [busy, setBusy] = useState(''); const [message, setMessage] = useState('');
  const refresh = async () => { const response = await fetch('/api/credentials'); if (!response.ok) throw new Error('Credential service unavailable.'); setProviders((await response.json()).providers || []); };
  useEffect(() => { refresh().catch((error) => setMessage(error.message)); }, []);
  const patchProvider = (next) => setProviders((items) => items.map((item) => item.id === next.id ? next : item));
  async function add(provider) { const draft = drafts[provider.id] || {}; if (!draft.value?.trim()) { setMessage(`Enter a ${provider.label} key first.`); return; } setBusy(`add:${provider.id}`); try { const response = await fetch('/api/credentials', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ providerId: provider.id, value: draft.value, label: draft.label }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Credential could not be saved.'); patchProvider(data.provider); setDrafts((all) => ({ ...all, [provider.id]: {} })); setMessage(`${provider.label} credential saved server-side.`); } catch (error) { setMessage(error.message); } finally { setBusy(''); } }
  async function update(providerId, key, changes) { setBusy(key.slot); try { const response = await fetch(`/api/credentials/${encodeURIComponent(key.slot)}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ providerId, ...changes }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Credential could not be updated.'); patchProvider(data.provider); } catch (error) { setMessage(error.message); } finally { setBusy(''); } }
  async function verify(providerId, key) { setBusy(`verify:${key.slot}`); setMessage(''); try { const response = await fetch(`/api/credentials/${encodeURIComponent(key.slot)}/verify`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ providerId }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Verification failed.'); await refresh(); setMessage(data.verification.status === 'valid' ? 'Credential accepted by the provider.' : `Provider returned: ${stateLabel[data.verification.status] || data.verification.status}`); } catch (error) { setMessage(error.message); } finally { setBusy(''); } }
  async function remove(providerId, key) { setBusy(`remove:${key.slot}`); try { const response = await fetch(`/api/credentials/${encodeURIComponent(key.slot)}?provider=${encodeURIComponent(providerId)}`, { method: 'DELETE' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Credential could not be removed.'); patchProvider(data.provider); } catch (error) { setMessage(error.message); } finally { setBusy(''); } }
  return <section className="workspace-panel settings-section full credential-manager"><div className="panel-label">Provider credentials</div><p className="setting-help">Keys stay in the server-only credential store. Verification makes a minimal authenticated provider request; text in a field is never treated as proof.</p><div className="provider-credentials">{providers.map((provider) => <article key={provider.id}><header><div><h3>{provider.label}</h3><small>{provider.keys.filter((key) => key.configured && key.enabled).length} active key(s)</small></div></header>{provider.keys.map((key) => <div className="credential-row" key={key.slot}><input aria-label={`${key.label} label`} value={key.label} onChange={(event) => setProviders((items) => items.map((item) => item.id !== provider.id ? item : { ...item, keys: item.keys.map((entry) => entry.slot === key.slot ? { ...entry, label: event.target.value } : entry) }))} onBlur={() => update(provider.id, key, { label: key.label, enabled: key.enabled })} /><div className="secret-mask"><input aria-label={`${key.label} credential`} type={shown[key.slot] ? 'text' : 'password'} value={key.configured ? 'credential-is-stored' : ''} readOnly /><button type="button" onClick={() => setShown((value) => ({ ...value, [key.slot]: !value[key.slot] }))}>{shown[key.slot] ? 'Hide' : 'Show'}</button></div><span className={`verification-state ${key.verification.status}`}>{busy === `verify:${key.slot}` ? 'Verifying…' : stateLabel[key.verification.status] || 'Not verified'}</span><label className="key-enabled"><input type="checkbox" checked={key.enabled} onChange={(event) => update(provider.id, key, { label: key.label, enabled: event.target.checked })} /> Enabled</label><button type="button" className="secondary-action" disabled={!key.configured || Boolean(busy)} onClick={() => verify(provider.id, key)}>Verify</button><button type="button" className="quiet-danger" disabled={!key.configured || Boolean(busy)} onClick={() => remove(provider.id, key)}>Remove</button></div>)}<div className="credential-add"><input value={drafts[provider.id]?.label || ''} onChange={(event) => setDrafts((all) => ({ ...all, [provider.id]: { ...all[provider.id], label: event.target.value } }))} placeholder={`${provider.label} Backup`} /><input type="password" value={drafts[provider.id]?.value || ''} onChange={(event) => setDrafts((all) => ({ ...all, [provider.id]: { ...all[provider.id], value: event.target.value } }))} placeholder="Paste new API key" /><button type="button" className="primary-action" disabled={Boolean(busy)} onClick={() => add(provider)}>+ Add key</button></div></article>)}</div>{message && <p className="routing-summary">{message}</p>}<LegacyConnectionSecrets /></section>;
}

function LegacyConnectionSecrets() {
  const fields = ['OBSIDIAN_VAULT_PATH', 'COMPOSIO_API_KEY', 'SLACK_BOT_TOKEN', 'SLACK_CHANNEL_ID', 'SLACK_SIGNING_SECRET', 'SLACK_WEBHOOK_URL', 'SEARCH_PROVIDER_KEY', 'JARVIS_AUTH_TOKEN']; const [values, setValues] = useState({}); const [configured, setConfigured] = useState({}); const [saved, setSaved] = useState('');
  useEffect(() => { fetch('/api/config').then((response) => response.ok ? response.json() : {}).then(setConfigured).catch(() => {}); }, []);
  async function save() { const response = await fetch('/api/config', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify(Object.fromEntries(Object.entries(values).filter(([, value]) => value))) }); setSaved(response.ok ? 'Saved.' : 'Could not save.'); if (response.ok) { setConfigured(await response.json()); setValues({}); } }
  return <details className="advanced-secrets"><summary>Integration and local service settings</summary><div className="form-grid">{fields.map((field) => <label key={field}>{field.replaceAll('_', ' ')}<input type={/KEY|TOKEN|SECRET/.test(field) ? 'password' : 'text'} value={values[field] || ''} onChange={(event) => setValues((all) => ({ ...all, [field]: event.target.value }))} placeholder={configured[field]?.configured ? 'Configured · enter to replace' : 'Not configured'} /></label>)}</div><button className="secondary-action" type="button" onClick={save}>Save settings</button>{saved && <span className="model-count">{saved}</span>}</details>;
}

export function AppearanceManagerPanel() {
  const [appearance, setAppearance] = useAppearance(); const [message, setMessage] = useState('');
  const selectTheme = (theme) => setAppearance((current) => ({ ...current, theme, accent: THEME_PRESETS[theme]?.accent || current.accent }));
  async function fontUpload(file) { if (!file) return; try { const name = await saveCustomFont(file); setAppearance((current) => ({ ...current, fontFamily: 'Custom', customFontName: name })); setMessage(`${name} loaded locally.`); } catch (error) { setMessage(error.message); } }
  return <section className="workspace-panel settings-section full appearance-manager"><div className="panel-label">Interface appearance</div><p className="setting-help">One accent controls the Brain, nodes, links, navigation, controls, and HUD emphasis. Settings persist locally.</p><div className="theme-swatches">{Object.entries(THEME_PRESETS).filter(([id]) => id !== 'custom').map(([id, theme]) => <button key={id} className={appearance.theme === id ? 'selected' : ''} onClick={() => selectTheme(id)}><i style={{ background: theme.accent }} /><span>{theme.label}</span></button>)}</div><div className="form-grid appearance-controls"><label>Custom accent<div className="colour-control"><input type="color" value={appearance.accent} onChange={(event) => setAppearance((current) => ({ ...current, theme: 'custom', accent: event.target.value }))} /><input value={appearance.accent} onChange={(event) => /^#[0-9a-f]{0,6}$/i.test(event.target.value) && setAppearance((current) => ({ ...current, theme: 'custom', accent: event.target.value }))} /></div></label><label>Font family<select value={appearance.fontFamily} onChange={(event) => setAppearance((current) => ({ ...current, fontFamily: event.target.value }))}>{FONT_OPTIONS.map((font) => <option key={font}>{font}</option>)}</select></label><label>Upload custom font<input type="file" accept=".ttf,.otf,.woff,.woff2" onChange={(event) => fontUpload(event.target.files?.[0])} /><small>{appearance.customFontName || 'TTF, OTF, WOFF, WOFF2 · max 4 MB'}</small></label><label>Interface scale <b>{appearance.fontSize}px</b><input type="range" min="13" max="21" value={appearance.fontSize} onChange={(event) => setAppearance((current) => ({ ...current, fontSize: Number(event.target.value) }))} /></label><label>Heading scale <b>{Math.round(appearance.headingScale * 100)}%</b><input type="range" min="0.9" max="1.25" step="0.05" value={appearance.headingScale} onChange={(event) => setAppearance((current) => ({ ...current, headingScale: Number(event.target.value) }))} /></label><label>HUD label scale <b>{Math.round(appearance.labelScale * 100)}%</b><input type="range" min="0.9" max="1.25" step="0.05" value={appearance.labelScale} onChange={(event) => setAppearance((current) => ({ ...current, labelScale: Number(event.target.value) }))} /></label></div><div className="model-actions"><button type="button" className="secondary-action" onClick={() => setAppearance(DEFAULTS)}>Reset default</button>{message && <span className="model-count">{message}</span>}</div></section>;
}

const CHANNELS = [['whatsapp', 'WhatsApp', '+91 phone number'], ['instagram', 'Instagram', 'Username / thread ID'], ['discord', 'Discord', 'User / channel ID'], ['slack', 'Slack', 'User / channel ID'], ['gmail', 'Gmail', 'Email address']];
export function ContactManagerPanel() {
  const [contacts, setContacts] = useState([]); const [query, setQuery] = useState(''); const [busy, setBusy] = useState(''); const [message, setMessage] = useState('');
  const refresh = () => fetch('/api/contacts').then((response) => response.ok ? response.json() : Promise.reject(new Error('Contact library unavailable.'))).then((data) => setContacts(data.contacts || [])).catch((error) => setMessage(error.message));
  useEffect(refresh, []);
  const update = (id, patch) => setContacts((items) => items.map((item) => item.id === id ? { ...item, ...patch } : item));
  const updateEndpoint = (id, platform, value) => setContacts((items) => items.map((item) => item.id === id ? { ...item, endpoints: { ...(item.endpoints || {}), [platform]: value } } : item));
  function add() { setContacts((items) => [{ id: `new-${Date.now()}`, name: '', aliases: [], category: '', notes: '', endpoints: {} }, ...items]); }
  async function save(contact) { setBusy(contact.id); try { const payload = { ...(String(contact.id).startsWith('new-') ? {} : { id: contact.id }), name: contact.name, aliases: contact.aliases || [], category: contact.category || '', notes: contact.notes || '', endpoints: contact.endpoints || {} }; const response = await fetch('/api/contacts', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Save failed.'); setContacts((items) => items.map((item) => item.id === contact.id ? data.contact : item)); setMessage(`${data.contact.name} saved.`); } catch (error) { setMessage(error.message); } finally { setBusy(''); } }
  async function remove(contact) { if (String(contact.id).startsWith('new-')) return setContacts((items) => items.filter((item) => item.id !== contact.id)); setBusy(contact.id); try { const response = await fetch(`/api/contacts/${encodeURIComponent(contact.id)}`, { method: 'DELETE' }); const data = await response.json(); if (response.status === 202) setMessage('Deletion is waiting in Approvals.'); else if (!response.ok) throw new Error(data.error?.message || data.error || 'Delete failed.'); else setContacts((items) => items.filter((item) => item.id !== contact.id)); } catch (error) { setMessage(error.message); } finally { setBusy(''); } }
  const visible = contacts.filter((contact) => `${contact.name} ${(contact.aliases || []).join(' ')} ${contact.category || ''}`.toLowerCase().includes(query.toLowerCase()));
  return <section className="workspace-panel settings-section full contact-library"><div className="routing-head"><div><div className="panel-label">People &amp; contact aliases</div><p className="setting-help">Saved identifiers remain local. JARVIS asks which platform to use when you do not specify one.</p></div><div className="contact-actions"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search contacts" /><button type="button" className="primary-action" onClick={add}>+ Add Contact</button></div></div><div className="contact-grid">{visible.map((contact) => <article key={contact.id}><div className="contact-card-head"><label>Name<input value={contact.name || ''} onChange={(event) => update(contact.id, { name: event.target.value })} /></label><div><button type="button" className="secondary-action" disabled={busy === contact.id || !contact.name.trim()} onClick={() => save(contact)}>{busy === contact.id ? 'Saving…' : 'Save'}</button><button type="button" className="quiet-danger" onClick={() => remove(contact)}>Delete</button></div></div><div className="contact-basics"><label>Relationship / category<input value={contact.category || ''} onChange={(event) => update(contact.id, { category: event.target.value })} placeholder="Family, work, tuition" /></label><label>Aliases<input value={(contact.aliases || []).join(', ')} onChange={(event) => update(contact.id, { aliases: event.target.value.split(',').map((item) => item.trim()).filter(Boolean) })} placeholder="papa, dad" /></label></div><div className="contact-endpoints">{CHANNELS.map(([platform, label, placeholder]) => <label key={platform}>{label}<input value={contact.endpoints?.[platform] || ''} onChange={(event) => updateEndpoint(contact.id, platform, event.target.value)} placeholder={placeholder} /></label>)}</div><label>Notes<textarea value={contact.notes || ''} onChange={(event) => update(contact.id, { notes: event.target.value })} placeholder="Useful context about this person" /></label></article>)}</div>{message && <p className="routing-summary">{message}</p>}</section>;
}
